version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: timesheet
    volumes:
      - timesheetvol:/var/lib/mysql
    ports:
      - "3306:3306"

  timesheet-app:
    build: .
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/timesheet
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql

volumes:
  timesheetvol:
