services:
  mysqldb2:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: timesheetdb
    ports:
      - "3307:3306"
    volumes:
      - timesheetvol2:/var/lib/mysql

  timesheet:
    depends_on:
      - mysqldb2
    image: timesheet-project-timesheet-app
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb2:3306/timesheetdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass123

volumes:
  timesheetvol2:
